package com.jana.url_shortener.service;

import com.jana.url_shortener.dto.ShortenUrlRequest;
import com.jana.url_shortener.dto.UrlResponse;
import com.jana.url_shortener.entity.Role;
import com.jana.url_shortener.entity.UrlMapping;
import com.jana.url_shortener.entity.User;
import com.jana.url_shortener.exception.ResourceNotFoundException;
import com.jana.url_shortener.repository.UrlMappingRepository;
import com.jana.url_shortener.repository.UserRepository;
import com.jana.url_shortener.security.CustomUserDetails;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.Collections;
import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UrlServiceTest {

    @Mock
    private UrlMappingRepository urlMappingRepository;

    @Mock
    private UserRepository userRepository;

    @Mock
    private RedisCacheService redisCacheService;

    @Mock
    private AnalyticsService analyticsService;

    @InjectMocks
    private UrlService urlService;

    private User testUser;
    private CustomUserDetails customUserDetails;

    @BeforeEach
    void setUp() {

        testUser = User.builder()
                .id(1L)
                .email("test@domain.com")
                .password("encoded_pass")
                .role(Role.ROLE_USER)
                .build();

        customUserDetails = new CustomUserDetails(
                testUser.getId(),
                testUser.getEmail(),
                testUser.getPassword(),
                Collections.emptyList()
        );

        UsernamePasswordAuthenticationToken authentication =
                new UsernamePasswordAuthenticationToken(
                        customUserDetails,
                        null,
                        customUserDetails.getAuthorities()
                );

        SecurityContextHolder.getContext()
                .setAuthentication(authentication);
    }

    @AfterEach
    void tearDown() {
        SecurityContextHolder.clearContext();
    }

    // CREATE SHORT URL
    @Test
    @DisplayName("createShortUrl: should generate Base62 short code and cache URL")
    void createShortUrl_AutoGenerated_Success() {

        ShortenUrlRequest request =
                new ShortenUrlRequest(
                        "https://github.com",
                        null,
                        30
                );

        when(userRepository.getReferenceById(1L))
                .thenReturn(testUser);

        UrlMapping savedMapping = UrlMapping.builder()
                .id(125L)
                .originalUrl(request.longUrl())
                .user(testUser)
                .expiresAt(LocalDateTime.now().plusDays(30))
                .build();

        when(urlMappingRepository.save(any(UrlMapping.class)))
                .thenReturn(savedMapping);

        UrlResponse response =
                urlService.createShortUrl(request);

        assertNotNull(response);
        assertEquals("21", response.shortCode());
        assertEquals(
                "http://localhost:8080/21",
                response.shortUrl()
        );

        verify(userRepository)
                .getReferenceById(1L);

        verify(urlMappingRepository)
                .save(any(UrlMapping.class));

        verify(redisCacheService)
                .cacheUrl(
                        eq("21"),
                        eq("https://github.com"),
                        any(Duration.class)
                );
    }

    @Test
    @DisplayName("createShortUrl: should create URL using custom alias")
    void createShortUrl_CustomAlias_Success() {

        ShortenUrlRequest request =
                new ShortenUrlRequest(
                        "https://github.com",
                        "custom-link",
                        null
                );

        when(userRepository.getReferenceById(1L))
                .thenReturn(testUser);

        when(urlMappingRepository.existsByShortCode("custom-link"))
                .thenReturn(false);

        UrlMapping savedMapping = UrlMapping.builder()
                .id(1L)
                .shortCode("custom-link")
                .originalUrl(request.longUrl())
                .user(testUser)
                .build();

        when(urlMappingRepository.save(any(UrlMapping.class)))
                .thenReturn(savedMapping);

        UrlResponse response =
                urlService.createShortUrl(request);

        assertNotNull(response);
        assertEquals(
                "custom-link",
                response.shortCode()
        );

        verify(urlMappingRepository)
                .existsByShortCode("custom-link");

        verify(urlMappingRepository)
                .save(any(UrlMapping.class));

        verify(redisCacheService)
                .cacheUrl(
                        eq("custom-link"),
                        eq("https://github.com"),
                        any(Duration.class)
                );
    }

    @Test
    @DisplayName("createShortUrl: should reject reserved keyword")
    void createShortUrl_ReservedKeyword_ThrowsException() {

        ShortenUrlRequest request =
                new ShortenUrlRequest(
                        "https://github.com",
                        "actuator",
                        null
                );

        when(userRepository.getReferenceById(1L))
                .thenReturn(testUser);

        IllegalArgumentException exception =
                assertThrows(
                        IllegalArgumentException.class,
                        () -> urlService.createShortUrl(request)
                );

        assertTrue(
                exception.getMessage()
                        .contains("system-reserved keyword")
        );

        verify(urlMappingRepository, never())
                .save(any());

        verify(redisCacheService, never())
                .cacheUrl(
                        any(),
                        any(),
                        any()
                );
    }

    @Test
    @DisplayName("createShortUrl: should reject duplicate custom alias")
    void createShortUrl_DuplicateAlias_ThrowsException() {

        ShortenUrlRequest request =
                new ShortenUrlRequest(
                        "https://github.com",
                        "existing-alias",
                        null
                );

        when(userRepository.getReferenceById(1L))
                .thenReturn(testUser);

        when(urlMappingRepository.existsByShortCode("existing-alias"))
                .thenReturn(true);

        IllegalArgumentException exception =
                assertThrows(
                        IllegalArgumentException.class,
                        () -> urlService.createShortUrl(request)
                );

        assertTrue(
                exception.getMessage()
                        .contains("Custom alias already exists")
        );

        verify(urlMappingRepository)
                .existsByShortCode("existing-alias");

        verify(urlMappingRepository, never())
                .save(any());

        verify(redisCacheService, never())
                .cacheUrl(
                        any(),
                        any(),
                        any()
                );
    }

    // REDIRECT / CACHE
    @Test
    @DisplayName("getOriginalUrlAndValidate: Redis hit should avoid database query")
    void getOriginalUrl_CacheHit_Success() {

        when(redisCacheService.getOriginalUrl("abc"))
                .thenReturn(
                        Optional.of("https://cached-target.com")
                );

        String targetUrl =
                urlService.getOriginalUrlAndValidate("abc");

        assertEquals(
                "https://cached-target.com",
                targetUrl
        );

        verify(redisCacheService)
                .getOriginalUrl("abc");

        verify(urlMappingRepository, never())
                .findByShortCode(any());

        verify(analyticsService)
                .incrementClickCountAsync("abc");
    }

    @Test
    @DisplayName("getOriginalUrlAndValidate: Redis miss should query database and populate cache")
    void getOriginalUrl_CacheMiss_Success() {

        when(redisCacheService.getOriginalUrl("abc"))
                .thenReturn(Optional.empty());

        UrlMapping mapping = UrlMapping.builder()
                .shortCode("abc")
                .originalUrl("https://db-target.com")
                .expiresAt(LocalDateTime.now().plusDays(1))
                .build();

        when(urlMappingRepository.findByShortCode("abc"))
                .thenReturn(Optional.of(mapping));

        String targetUrl =
                urlService.getOriginalUrlAndValidate("abc");

        assertEquals(
                "https://db-target.com",
                targetUrl
        );

        verify(redisCacheService)
                .getOriginalUrl("abc");

        verify(urlMappingRepository)
                .findByShortCode("abc");

        verify(redisCacheService)
                .cacheUrl(
                        eq("abc"),
                        eq("https://db-target.com"),
                        any(Duration.class)
                );

        verify(analyticsService)
                .incrementClickCountAsync("abc");
    }

    @Test
    @DisplayName("getOriginalUrlAndValidate: expired URL should throw exception")
    void getOriginalUrl_Expired_ThrowsException() {

        when(redisCacheService.getOriginalUrl("expiredCode"))
                .thenReturn(Optional.empty());

        UrlMapping expiredMapping = UrlMapping.builder()
                .shortCode("expiredCode")
                .originalUrl("https://target.com")
                .expiresAt(LocalDateTime.now().minusDays(1))
                .build();

        when(urlMappingRepository.findByShortCode("expiredCode"))
                .thenReturn(Optional.of(expiredMapping));

        IllegalArgumentException exception =
                assertThrows(
                        IllegalArgumentException.class,
                        () -> urlService.getOriginalUrlAndValidate(
                                "expiredCode"
                        )
                );

        assertTrue(
                exception.getMessage()
                        .contains("Short URL has expired")
        );

        verify(redisCacheService)
                .getOriginalUrl("expiredCode");

        verify(urlMappingRepository)
                .findByShortCode("expiredCode");

        verify(analyticsService, never())
                .incrementClickCountAsync("expiredCode");
    }

    // ANALYTICS / OWNERSHIP
    @Test
    @DisplayName("getUrlAnalytics: should throw exception when URL does not exist")
    void getUrlAnalytics_NotFound_ThrowsException() {

        when(urlMappingRepository.findById(999L))
                .thenReturn(Optional.empty());

        assertThrows(
                ResourceNotFoundException.class,
                () -> urlService.getUrlAnalytics(999L)
        );

        verify(urlMappingRepository)
                .findById(999L);
    }

    @Test
    @DisplayName("getUrlAnalytics: should deny access to another user's URL")
    void getUrlAnalytics_UnauthorizedUser_ThrowsAccessDenied() {

        User differentUser = User.builder()
                .id(99L)
                .email("other@domain.com")
                .role(Role.ROLE_USER)
                .build();

        UrlMapping mapping = UrlMapping.builder()
                .id(10L)
                .shortCode("xyz")
                .user(differentUser)
                .build();

        when(urlMappingRepository.findById(10L))
                .thenReturn(Optional.of(mapping));

        AccessDeniedException exception =
                assertThrows(
                        AccessDeniedException.class,
                        () -> urlService.getUrlAnalytics(10L)
                );

        assertTrue(
                exception.getMessage()
                        .contains("You do not have permission")
        );

        verify(urlMappingRepository)
                .findById(10L);
    }
}